name: Build, Test, and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test tests/Application.Tests.Unit/Application.Tests.Unit.csproj --configuration Release --no-build

    - name: Publish
      run: dotnet publish src/WinForm/WinForm.csproj

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: WinForm
        path: WinForm
